// ----------------------------------------------AppColors---------------------------------------
export const AppColors = {
  primary: '#9C1256',
  secondary: '#6962AD',
  red: 'red',
  gray: '#D9D9D9',
  dark_gray: '#707070',
  black: '#000000',
  white: '#FFFFFF',
  yellow: '#FEB747',
  linearDarkGradient: ['#171575', '#000000'],
  darkYellow: '#edc531',
  lightGrayShade: '#242131',
  grayShade: '#f0f0f0',
  gold: '#FBCB69',
  silverShade: '#8D8B94',
  tabColor: '#9B1256',
  elementBackground: '#fff',
  textColor: '#212121',
  skyBlue: '#C5E3FF',
  lightYellow: '#FFF2DE',
  jj: '#CE4488',
};

// ----------------------------------------------AppRoutes---------------------------------------
export const routes = {
  //DrawerMainScreens----
  Drawer_Stack: 'DrawerStack',
  Kundali_Top_Tab_Stack: 'KundaliTopTabStack',
  Chat_Tab_Stack: 'ChatTabStack',
  Call_Tab_Stack: 'CallTabStack',
  VideoCall_TabStack: 'VideoCallTabStack',

  //kundali Top Tab Screens--
  Basic: 'Basic',
  Dasha: 'Dasha',
  Lagna: 'Lagna',
  Navamsa: 'Navamsa',
  Transit: 'Transit',
  Planetdetails: 'Planet Details',
  Manglikdosh: 'Manglikdosh',
  Pitradosh: 'Pitradosh',
  Panchang: 'Panchang',

  //mainScreens----
  Home: 'Home',
  Orders: 'Orders',
  WaitList: 'WaitList',
  Offer: 'Offer',
  Followers: 'Followers',
  Wallet: 'Wallet',
  Call_History: 'CallHistory',
  ChatHistory: 'ChatHistory',
  MyReviews: 'MyReviews',
  Settings: 'Settings',
  Profile: 'Profile',
  Performance_Screens: 'PerformanceScreens',
  Notice: 'Notice',
  More: 'More',
  Live_Event: 'LiveEvent',
  View_All_Training_Reels: 'ViewAllTrainingReels',
  Play_Reel: 'PlayReel',
  View_Image_Screen: 'ViewImageScreen',
  VideoCall_Screen: 'VideoCallScreen',
  GoLive: 'GoLive',
  PrivacyPolicy: 'PrivacyPolicy',
  HelpAndSupport: 'HelpAndSupport',
  AgoraLiveEvent: 'AgoraLiveEvent',
  Top_Astrologers: 'TopAstrologers',

  // blog--
  Blog_Screen: 'BlogScreen',
  Add_Blog_Screen: 'AddBlogScreen',
  //pooja--
  Add_Pooja: 'AddPooja',
  Pooja_Screen: 'PoojaScreen',

  // bank---
  Bank_Details: 'BankDetails',
  Add_Edit_Bank_Details: 'AddEditBankDetails',

  View_Image_Screen: 'ViewImageScreen',
  Update_Phone_Number: 'UpdatePhoneNumber',
  PaySlip: 'PaySlip',
  Terms_And_Conditions: 'TermsAndConditions',
  Create_Offer: 'CreateOffer',
  User_Chat_Screen: 'UserChatScreen',
  Call_With_User: 'CallWithUser',
  Quick_Chat: 'Quick Chat',
  Add_Quick_Chat: 'Add Quick Chat',
  particular_Chat_History: 'particularChatHistory',

  //authScreens----
  Splash: 'Splash',
  login: 'login',
  SignUp: 'SignUp',
  Otp_Verification: 'OtpVerification',
  Create_Profile: 'CreateProfile',
  UnderReview_Screen: 'UnderReviewScreen',
};

// --------------------------------------App Consants of AsyncStorage-------------------------------
export const CONSTANTS_ASYNC = {
  TOKEN: 'TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  IS_DARKMODE: 'IS_DARKMODE',
};

export const AGORA_CONSTANTS = {
  APP_ID: '1161b67f936f4d2cac80767d4390ecea',
  ARORA_TOKEN: 'ARORA_TOKEN',
};

// -------------------------------------- Consants of keyboardType-------------------------------
export const keyboardType = {
  namePhonePad: 'name-phone-pad',
  default: 'default',
  phonePad: 'phone-pad',
};

export const dummyChat = [
  {
    id: '1',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Hello, how can I help you?',
      from: 'astrologer',
    },
  },
  {
    id: '2',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'I need some advice regarding my career.',
      from: 'user',
    },
  },
  {
    id: '3',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Sure, please tell me your birth details.',
      from: 'astrologer',
    },
  },
  {
    id: '4',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'I was born on April 5, 1990.',
      from: 'user',
    },
  },
  {
    id: '5',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Thank you. Could you also provide the time and place of birth?',
      from: 'astrologer',
    },
  },
  {
    id: '6',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'I was born at 2:30 PM in New York.',
      from: 'user',
    },
  },
  {
    id: '7',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Great, let me analyze your chart. Please wait a moment.',
      from: 'astrologer',
    },
  },
  {
    id: '8',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Sure, take your time.',
      from: 'user',
    },
  },
  {
    id: '9',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message:
        'Based on your birth details, it looks like you have a strong career in the arts or communication.',
      from: 'astrologer',
    },
  },
  {
    id: '10',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message:
        'That sounds interesting! I have been thinking about pursuing a career in writing.',
      from: 'user',
    },
  },
  {
    id: '11',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message:
        'That’s a good choice. Your chart shows strong potential in creative fields.',
      from: 'astrologer',
    },
  },
  {
    id: '12',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Thank you for the guidance. I feel more confident now.',
      from: 'user',
    },
  },
  {
    id: '13',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'You’re welcome! Do you have any other questions?',
      from: 'astrologer',
    },
  },
  {
    id: '14',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'Not at the moment. Thanks again!',
      from: 'user',
    },
  },
  {
    id: '15',
    message: {
      sender: 'user1',
      astrologer: 'astrologer',
      message: 'My pleasure. Have a great day!',
      from: 'astrologer',
    },
  },
];

const data = {
  id: 7,
  user_details: {
    id: 749,
    created_at: '2024-05-30T09:10:19.548898Z',
    updated_at: '2024-05-30T09:10:19.549222Z',
    name: 'Shantanu',
    state: 'Bihar',
    city: 'Madhepura',
    country: 'India',
    dob: '1997-03-16',
    tob: '05:27:00',
    tz: '5.5',
    user: 61,
  },
  match: null,
  pitradosh: {
    status: 200,
    response: {
      is_dosha_present: true,
      bot_response:
        'Pitra dosha happens when Saturn / Rahu is conjunct or aspects sun or moon.  This occurs in your horoscope and thus this dosha is present in your birth chart.',
      effects: [
        'Children can face mental and physical disabilities. Either later or from the day of the birth.',
        'Un-favorable environment and arguments on small things with life-partner.',
        'Sometimes one is not able to marry at the correct time. Delay in marriage.',
        'The person face financial and physical problems due to continuous sickness.',
        'The person is having Pitra Dosh, if he is not able to achieve success in any work he starts.',
        'Continuous scarcity and financial problems.',
        'If the person or any other family member see dreams related to snakes hint towards this dosha.',
        'One can have a dream of ancestors asking you for food or clothes.',
      ],
      remedies: [
        'Offer water to Banyan tree regularly.',
        'Keep fasts to reduce the effects of Dosha.',
        'Organize Pooja or Mantra Jap to nullify the effects of past sinful activities done by ancestors.',
        'Give food to Brahmins on every Amavasya.',
        'Donate food, blankets, bedding and clothes on the day of Ardh-Kumbha-Snaan.',
        'Give food and milk to cows, street dogs, crows and ants.',
        'Complete Trapandi Shraad.',
        'Give help to poor, needy and old people as much as possible.',
        'Chant the mantras of Devi Kaalika Stotram. Especially on Navratri.',
        'Do Snaan at various religious places like, Ujjain, Nasik, Ganga Sagar, Haridwar, etc.',
        'Offer water mixed with sesame seeds to the rising Sun regularly and chant Gayatri Mantra.',
      ],
    },
  },
  manglikdosh: {
    status: 200,
    response: {
      manglik_by_mars: true,
      factors: [
        'Manglik dosha is created by Mars in the 8th house in Lagna chart, Mars in the 4th house in Moon chart, Mars-Venus association, and Mars-Saturn association.',
        'manglik dosha is created by rahu-ketu in 8-2 axis and saturn in house 2.',
      ],
      bot_response: 'You are 89% manglik. ',
      manglik_by_saturn: true,
      manglik_by_rahuketu: true,
      aspects: [
        'Rahu in the 8th is aspecting the 12th and 4th',
        'Ketu in the 2nd is aspecting the 8th',
        'Saturn in the 2nd is aspecting the 4th and 8th',
      ],
      score: 89,
    },
  },
  panchang: {
    status: 200,
    response: {
      day: {
        name: 'Sunday',
      },
      tithi: {
        name: 'Ashtami',
        number: 8,
        next_tithi: 'Navami',
        type: 'Shukla',
        diety: 'Durga',
        start: 'Sat Mar 15 1997 4:49:02 PM',
        end: 'Sun Mar 16 1997 5:44:01 PM',
        meaning: 'Eighth day after Amavasya (new moon) or Purnima (full moon).',
        special:
          'Good for work related to spiritual practices and seeking blessings.',
      },
      nakshatra: {
        name: 'Mrigashira',
        number: 5,
        lord: 'Mars',
        diety: 'Soma',
        start: 'Sat Mar 15 1997 1:27:42 PM',
        next_nakshatra: 'Ardra',
        end: 'Sun Mar 16 1997 2:51:54 PM',
        meaning:
          "Deer's head. Symbolizes exploration, searching, and curiosity.",
        special:
          'Good for activities related to hunting, tracking, and exploration.',
        summary:
          'This nakshatra is of a mixed quality. Good for immediate actions, competition, work with metals. It is suitable to perform the routine activities, day-to-day duties, but it is not recommended to start new important deeds. Consult an astrologer for more information',
      },
      karana: {
        name: 'Bawa',
        number: 1,
        type: 'Benefic',
        lord: 'Surya',
        diety: 'Indra',
        start: 'Sun Mar 16 1997 5:10:59 AM',
        end: 'Sun Mar 16 1997 5:44:00 PM',
        special:
          'Good for any development projects, expansion, display of strength',
        next_karana: 'Balava',
      },
      yoga: {
        name: 'Ayushman',
        number: 3,
        start: 'Sat Mar 15 1997 5:33:35 PM',
        end: 'Sun Mar 16 1997 5:10:31 PM',
        next_yoga: 'Saubhagya',
        meaning:
          'Long life. Associated with longevity, health, and well-being.',
        special: 'Good for activities that involve health and longevity.',
      },
      ayanamsa: {
        name: '23 49\'7"',
      },
      rasi: {
        name: 'Gemini',
      },
      advanced_details: {
        sun_rise: '5:52:16 AM',
        sun_set: '5:53:07 PM',
        moon_rise: '11:20:31 AM',
        moon_set: '1:04:03 AM',
        next_full_moon: 'Mon Mar 24 1997',
        next_new_moon: 'Mon Apr 07 1997',
        masa: {
          amanta_number: 12,
          amanta_date: 8,
          amanta_name: 'Phalguna',
          alternate_amanta_name: 'Panguni',
          amanta_start: 'Sun Mar 09 1997',
          amanta_end: 'Mon Apr 07 1997',
          adhik_maasa: false,
          ayana: 'Uttrayana',
          real_ayana: 'Uttrayana',
          tamil_month_num: 12,
          tamil_month: 'Panguni',
          tamil_day: 2,
          purnimanta_date: 23,
          purnimanta_number: 12,
          purnimanta_name: 'Phalguna',
          alternate_purnimanta_name: 'Panguni',
          purnimanta_start: 'Sat Feb 22 1997',
          purnimanta_end: 'Mon Mar 24 1997',
          moon_phase: '90/360',
          paksha: 'Shukla Paksha',
          ritu: 'Vasant',
          ritu_tamil: 'Ilavenil',
        },
        moon_yogini_nivas: 'North-East',
        ahargana: 1862058.244635,
        years: {
          kali: 5097,
          saka: 1918,
          vikram_samvaat: 2053,
          kali_samvaat_number: 11,
          kali_samvaat_name: 'Ishvara',
          vikram_samvaat_number: 23,
          vikram_samvaat_name: 'Virodhi',
          saka_samvaat_number: 10,
          saka_samvaat_name: 'Dhatri',
        },
        vaara: 'Ravi vaara',
        disha_shool: 'East',
        abhijit_muhurta: {
          start: '11:28:41 AM',
          end: '12:16:41 PM',
        },
      },
      rahukaal: '04:22 PM to 05:52 PM',
      gulika: '02:52 PM to 04:22 PM',
      yamakanta: '11:52 AM to 01:22 PM',
      date: 'Sun Mar 16 1997',
    },
  },
  planetdetails: {
    status: 200,
    response: {
      0: {
        name: 'As',
        full_name: 'Ascendant',
        local_degree: 22.015672370853167,
        global_degree: 322.01567237085317,
        progress_in_percentage: 73.38557456951055,
        rasi_no: 11,
        zodiac: 'Aquarius',
        house: 1,
        nakshatra: 'PurvaBhadra',
        nakshatra_lord: 'Jupiter',
        nakshatra_pada: 1,
        nakshatra_no: 25,
        zodiac_lord: 'Saturn',
        is_planet_set: false,
        lord_status: '-',
        basic_avastha: '-',
        is_combust: false,
      },
      1: {
        name: 'Su',
        full_name: 'Sun',
        local_degree: 1.625410684795611,
        global_degree: 331.6254106847956,
        progress_in_percentage: 5.41803561598537,
        rasi_no: 12,
        zodiac: 'Pisces',
        house: 2,
        speed_radians_per_day: 1.1522633744855795e-8,
        retro: false,
        nakshatra: 'PurvaBhadra',
        nakshatra_lord: 'Jupiter',
        nakshatra_pada: 4,
        nakshatra_no: 25,
        zodiac_lord: 'Jupiter',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Malefic',
      },
      2: {
        name: 'Mo',
        full_name: 'Moon',
        local_degree: 1.53827497155401,
        global_degree: 61.53827497155401,
        progress_in_percentage: 5.127583238513367,
        rasi_no: 3,
        zodiac: 'Gemini',
        house: 5,
        speed_radians_per_day: 1.4356031378600832e-7,
        retro: false,
        nakshatra: 'Mrigashira',
        nakshatra_lord: 'Mars',
        nakshatra_pada: 3,
        nakshatra_no: 5,
        zodiac_lord: 'Mercury',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Malefic',
        is_combust: false,
      },
      3: {
        name: 'Ma',
        full_name: 'Mars',
        local_degree: 3.465926723500786,
        global_degree: 153.4659267235008,
        progress_in_percentage: 11.553089078335953,
        rasi_no: 6,
        zodiac: 'Virgo',
        house: 8,
        speed_radians_per_day: -4.526748971193465e-9,
        retro: true,
        nakshatra: 'UttaraPhalguni',
        nakshatra_lord: 'Sun',
        nakshatra_pada: 3,
        nakshatra_no: 12,
        zodiac_lord: 'Mercury',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Malefic',
        is_combust: false,
      },
      4: {
        name: 'Me',
        full_name: 'Mercury',
        local_degree: 5.83755707288077,
        global_degree: 335.83755707288077,
        progress_in_percentage: 19.458523576269236,
        rasi_no: 12,
        zodiac: 'Pisces',
        house: 2,
        speed_radians_per_day: 2.3029192386831823e-8,
        retro: false,
        nakshatra: 'UttaraBhadra',
        nakshatra_lord: 'Saturn',
        nakshatra_pada: 1,
        nakshatra_no: 26,
        zodiac_lord: 'Jupiter',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Neutral',
        is_combust: true,
      },
      5: {
        name: 'Ju',
        full_name: 'Jupiter',
        local_degree: 18.14214578029214,
        global_degree: 288.14214578029214,
        progress_in_percentage: 60.47381926764046,
        rasi_no: 10,
        zodiac: 'Capricorn',
        house: 12,
        speed_radians_per_day: 2.3276748971194175e-9,
        retro: false,
        nakshatra: 'Sravana',
        nakshatra_lord: 'Moon',
        nakshatra_pada: 3,
        nakshatra_no: 22,
        zodiac_lord: 'Saturn',
        is_planet_set: false,
        basic_avastha: 'Vriddha',
        lord_status: 'Highly Malefic',
        is_combust: false,
      },
      6: {
        name: 'Ve',
        full_name: 'Venus',
        local_degree: 27.190133858249396,
        global_degree: 327.1901338582494,
        progress_in_percentage: 90.63377952749799,
        rasi_no: 11,
        zodiac: 'Aquarius',
        house: 1,
        speed_radians_per_day: 1.4416152263374312e-8,
        retro: false,
        nakshatra: 'PurvaBhadra',
        nakshatra_lord: 'Jupiter',
        nakshatra_pada: 3,
        nakshatra_no: 25,
        zodiac_lord: 'Saturn',
        is_planet_set: false,
        basic_avastha: 'Mritya',
        lord_status: 'Yogakaraka',
        is_combust: true,
      },
      7: {
        name: 'Sa',
        full_name: 'Saturn',
        local_degree: 14.570895684253856,
        global_degree: 344.57089568425386,
        progress_in_percentage: 48.569652280846185,
        rasi_no: 12,
        zodiac: 'Pisces',
        house: 2,
        speed_radians_per_day: 1.4306841563786086e-9,
        retro: false,
        nakshatra: 'UttaraBhadra',
        nakshatra_lord: 'Saturn',
        nakshatra_pada: 4,
        nakshatra_no: 26,
        zodiac_lord: 'Jupiter',
        is_planet_set: false,
        basic_avastha: 'Yuva',
        lord_status: 'Benefic',
        is_combust: true,
      },
      8: {
        name: 'Ra',
        full_name: 'Rahu',
        local_degree: 5.339261474074107,
        global_degree: 155.3392614740741,
        progress_in_percentage: 17.79753824691369,
        rasi_no: 6,
        zodiac: 'Virgo',
        house: 8,
        retro: true,
        nakshatra: 'UttaraPhalguni',
        nakshatra_lord: 'Sun',
        nakshatra_pada: 3,
        nakshatra_no: 12,
        zodiac_lord: 'Mercury',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Natural Malefic',
        is_combust: false,
      },
      9: {
        name: 'Ke',
        full_name: 'Ketu',
        local_degree: 5.339261474074078,
        global_degree: 335.3392614740741,
        progress_in_percentage: 17.797538246913593,
        rasi_no: 12,
        zodiac: 'Pisces',
        house: 2,
        retro: true,
        nakshatra: 'UttaraBhadra',
        nakshatra_lord: 'Saturn',
        nakshatra_pada: 1,
        nakshatra_no: 26,
        zodiac_lord: 'Jupiter',
        is_planet_set: false,
        basic_avastha: 'Bala',
        lord_status: 'Natural Malefic',
        is_combust: false,
      },
      birth_dasa: 'Mars>Me>Ju',
      current_dasa: 'Ju>Me>Ju',
      birth_dasa_time: '05/01/1993',
      current_dasa_time: ' 30/05/2024',
      lucky_gem: ['coral'],
      lucky_num: [9],
      lucky_colors: ['Silver', 'grey'],
      lucky_letters: ['V', 'K'],
      lucky_name_start: ['Ve', 'Vo', 'Ka', 'Kee'],
      rasi: 'Gemini',
      nakshatra: 'Mrigashira',
      nakshatra_pada: 3,
      panchang: {
        ayanamsa: 23.82298587180767,
        ayanamsa_name: 'Lahiri',
        day_of_birth: 'Sunday',
        day_lord: 'Sun',
        hora_lord: 'Mercury',
        sunrise_at_birth: '05:55:00',
        sunset_at_birth: '17:45:00',
        karana: 'Bawa',
        yoga: 'Ayushman',
        tithi: 'Ashtami',
      },
      ghatka_chakra: {
        rasi: 'Aquarius',
        tithi: ['2 (dvitiya)', '7 (saptami)', '12 (dwadasi)'],
        day: 'Monday',
        nakshatra: 'Swati',
        tatva: 'Prithvi (Earth)',
        lord: 'Mercury',
        same_sex_lagna: 'Cancer',
        opposite_sex_lagna: 'Capricorn',
      },
    },
  },
  nakshatravastu: null,
  nakshatra: null,
  chandra_rasi: null,
  soorya_rasi: null,
  zodiac: null,
  additional_info: null,
  papasamya: {
    status: 200,
    response: {
      rahu_papa: 9,
      sun_papa: 7.5,
      saturn_papa: 11.25,
      mars_papa: 36,
    },
  },
  mangdaldosh: {
    status: 400,
    response: 'Out of API calls - Upgrade Required',
  },
};
